const { GoogleSpreadsheet } = require('google-spreadsheet');


// Initialize the sheet - doc ID is the long id in the sheets URL
var doc;



async function initSheetReader() {
    doc = new GoogleSpreadsheet('1IxgcU8peq0fc-fbHqzB6MBUwP2zPHLt-jAkBFoPbiXc');

    // Initialize Auth - see https://theoephraim.github.io/node-google-spreadsheet/#/getting-started/authentication
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      //Les nouvelles lignes ne sont pas mises correctement, donc on corrige manuellement
      private_key: process.env.GOOGLE_PRIVATE_KEY.replace(/\\n/g, "\n"),
    });
}


module.exports = {
    initSheetReader
}